# Generated by Django 5.2.1 on 2025-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBInventory', '0002_rename_inventorytypes_tables_inventorytypestables'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
