# Generated by Django 5.2.1 on 2025-12-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBInventory', '0003_tabletest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletest',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
