# Generated by Django 5.2.1 on 2026-01-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBInventory', '0004_alter_tabletest_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitems',
            old_name='name',
            new_name='schema',
        ),
    ]
