# Generated by Django 5.2.1 on 2026-01-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBInventory', '0005_rename_name_inventoryitems_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=100)),
                ('schema', models.JSONField()),
            ],
        ),
    ]
